-- Convert shop_order to RANGE partitions by created_at (monthly).
-- Idempotent. Indexes created AFTER the DO block (separate transaction).

\timing on
\echo '=== Lab 03: partition shop_order ==='

DO $$
DECLARE
  already boolean;
  min_ts timestamptz;
  max_ts timestamptz;
  cur date;
  stop date;
  part_name text;
  from_ts text;
  to_ts text;
  y int;
  m int;
  fk_name text;
  max_id bigint;
  seq_reg regclass;
BEGIN
  SELECT EXISTS (
    SELECT 1
    FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'shop_order'
  ) INTO already;

  IF already THEN
    RAISE NOTICE 'shop_order already partitioned — skip conversion';
    RETURN;
  END IF;

  FOR fk_name IN
    SELECT c.conname
    FROM pg_constraint c
    WHERE c.conrelid = 'shop_orderitem'::regclass
      AND c.contype = 'f'
      AND c.confrelid = 'shop_order'::regclass
  LOOP
    EXECUTE format('ALTER TABLE shop_orderitem DROP CONSTRAINT %I', fk_name);
    RAISE NOTICE 'Dropped FK %', fk_name;
  END LOOP;

  CREATE TABLE shop_order_new (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    status varchar(20) NOT NULL,
    total_amount numeric(12, 2) NOT NULL,
    delivery_address text NOT NULL,
    comment text NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    customer_id bigint NOT NULL REFERENCES shop_customer(id) DEFERRABLE INITIALLY DEFERRED,
    PRIMARY KEY (id, created_at)
  ) PARTITION BY RANGE (created_at);

  SELECT MIN(created_at), MAX(created_at), COALESCE(MAX(id), 0)
  INTO min_ts, max_ts, max_id
  FROM shop_order;

  IF min_ts IS NULL THEN
    min_ts := date_trunc('month', NOW() - INTERVAL '24 months');
    max_ts := NOW();
  END IF;

  cur := date_trunc('month', min_ts)::date;
  stop := (date_trunc('month', NOW()) + INTERVAL '4 months')::date;

  WHILE cur < stop LOOP
    y := EXTRACT(YEAR FROM cur)::int;
    m := EXTRACT(MONTH FROM cur)::int;
    part_name := format('shop_order_%s_%s', lpad(y::text, 4, '0'), lpad(m::text, 2, '0'));
    from_ts := cur::text;
    to_ts := (cur + INTERVAL '1 month')::date::text;

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I PARTITION OF shop_order_new FOR VALUES FROM (%L) TO (%L)',
      part_name, from_ts, to_ts
    );
    cur := (cur + INTERVAL '1 month')::date;
  END LOOP;

  RAISE NOTICE 'Copying rows into partitioned table (may take several minutes)...';

  INSERT INTO shop_order_new (
    id, status, total_amount, delivery_address, comment,
    created_at, updated_at, customer_id
  )
  SELECT
    id, status, total_amount, delivery_address, comment,
    created_at, updated_at, customer_id
  FROM shop_order;

  seq_reg := pg_get_serial_sequence('shop_order_new', 'id');
  IF seq_reg IS NOT NULL AND max_id > 0 THEN
    PERFORM setval(seq_reg, max_id, true);
  END IF;

  DROP TABLE shop_order;
  ALTER TABLE shop_order_new RENAME TO shop_order;

  RAISE NOTICE 'shop_order converted; creating indexes next...';
END $$;

-- Separate statements = separate transactions (no pending trigger events)
CREATE INDEX IF NOT EXISTS idx_order_created_at ON shop_order (created_at);
CREATE INDEX IF NOT EXISTS idx_order_customer_status ON shop_order (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_order_cust_created_desc ON shop_order (customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_order_status_created ON shop_order (status, created_at);
CREATE INDEX IF NOT EXISTS idx_order_new_created ON shop_order (created_at) WHERE status = 'NEW';
CREATE INDEX IF NOT EXISTS shop_order_customer_id_f638df20 ON shop_order (customer_id);

\echo '--- partitions ---'
SELECT c.relname AS partition_name
FROM pg_inherits i
JOIN pg_class c ON c.oid = i.inhrelid
JOIN pg_class p ON p.oid = i.inhparent
WHERE p.relname = 'shop_order'
ORDER BY 1;

\echo '--- rows per partition (sample) ---'
SELECT tableoid::regclass AS partition_name, COUNT(*) AS rows
FROM shop_order
GROUP BY tableoid
ORDER BY partition_name
LIMIT 15;

SELECT COUNT(*) AS total_orders FROM shop_order;

SELECT EXISTS (
  SELECT 1 FROM pg_partitioned_table pt
  JOIN pg_class c ON c.oid = pt.partrelid
  WHERE c.relname = 'shop_order'
) AS is_partitioned;
