-- Daily events partitions for CreatePartitionsJob / PartitionHealthCheck demo.
-- Parent table name: lab_events (avoids clash with lab02 events experiments).

\timing on
\echo '=== Lab 03: setup lab_events (daily RANGE) ==='

DROP TABLE IF EXISTS lab_events CASCADE;

CREATE TABLE lab_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  payload TEXT,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);

-- Seed today-2 .. today+1 (leave today+2..+3 for the job / health demo)
DO $$
DECLARE
  d date := CURRENT_DATE - 2;
  stop date := CURRENT_DATE + 2;  -- exclusive: creates through tomorrow
  part text;
BEGIN
  WHILE d < stop LOOP
    part := 'lab_events_' || to_char(d, 'YYYY_MM_DD');
    EXECUTE format(
      'CREATE TABLE %I PARTITION OF lab_events FOR VALUES FROM (%L) TO (%L)',
      part, d::text, (d + 1)::text
    );
    d := d + 1;
  END LOOP;
END $$;

INSERT INTO lab_events (user_id, event_type, payload, created_at)
SELECT
  (g % 1000) + 1,
  (ARRAY['click', 'view', 'purchase'])[1 + (g % 3)],
  'x',
  (CURRENT_DATE - 1) + ((g % 86400) * INTERVAL '1 second')
FROM generate_series(1, 5000) g;

SELECT tableoid::regclass, COUNT(*) FROM lab_events GROUP BY 1 ORDER BY 1;
